[build]
target = "./avr-specs/avr-atmega328p.json"
# target = "/home/rust/rust/embedded/avr/avr-specs/avr-atmega328p.json"

[target.avr-atmega328p]
rustflags = [
    #
    "-Clink-arg=-nostartfiles",
    # "-Ctarget-cpu=atmega328p",
]

# [unstable]
# build-std = ["core"]
